# Stage 1: Build the Go binary
FROM golang:1.22 as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o main .

# Stage 2: Create a small image for running the Go binary
FROM scratch

WORKDIR /app

# Copy the Go binary from the builder stage
COPY --from=builder /app/main /app/

# Ensure the binary has executable permissions
RUN chmod +x /app/main

# Use a user with a known UID/GID
USER 1000:1000

EXPOSE 8080

ENTRYPOINT ["/app/main"]
