# Stage 1: Build the Go binary
FROM golang:1.22 as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o main .

# Stage 2: Create a small image for running the Go binary
FROM alpine:latest  # Using Alpine for debugging purposes

WORKDIR /app
COPY --from=builder /app/main /app/

USER 1000:1000
EXPOSE 8080

ENTRYPOINT ["/app/main"]
